version: '3.9'

services:
  film_catalog_app:
    build: ./
    command: ./film_catalog_app
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "5436:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db: